jobs:

  - name: dprk-pod-def
    type: manifest
    steps:
      - IN: dprk_app_img
      - TASK: managed

  - name: dprk_provision_cluster_and_secret
    type: runSh
    steps:
      - IN: dprk_dockerhub
      - IN: dprk_params
      - IN: dprk_cliConfig
        scopes:
          - gke
      - IN: dprk-pod-def
      - TASK:
        - script: |
            # check if the cluster already exists on GKE
            response=$(gcloud container clusters describe $DPRK_CLUSTER_NAME --zone $DPRK_CLICONFIG_POINTER_REGION || echo "ClusterNotFound")

            if [[ $response = "ClusterNotFound" ]]
            then
               echo "cluster not found, creating cluster"
               gcloud container clusters create $DPRK_CLUSTER_NAME --num-nodes=$DPRK_CLUSTER_NUM_NODES --machine-type=$DPRK_CLUSTER_MACHINE_TYPE
            else
               echo "cluster already exists, skipping creating cluster"
            fi

            # Delete and create the secret
            gcloud container clusters get-credentials $DPRK_CLUSTER_NAME --zone $DPRK_CLICONFIG_POINTER_REGION
            kubectl delete secret $DPRK_SECRET_KEY_NAME 2>/dev/null || echo "secret does not exist"
            kubectl create secret docker-registry $DPRK_SECRET_KEY_NAME --docker-username="$DPRK_DOCKERHUB_INTEGRATION_USERNAME" --docker-password="$DPRK_DOCKERHUB_INTEGRATION_PASSWORD" --docker-email="$DPRK_DOCKERHUB_INTEGRATION_EMAIL" --docker-server="$DPRK_DOCKERHUB_INTEGRATION_URL"/

  - name: dprk-pod-deploy
    type: deploy
    steps:
      - IN: dprk_imagepull_secrets
      - IN: dprk_cluster
      - IN: dprk-pod-def
      - IN: dprk_provision_cluster

  - name: dprk_provision_lb
    type: provision
    steps:
      - IN: dprk_lb
      - IN: dprk-pod-deploy
