jobs:

  - name: dprk-app-def
    type: manifest
    steps:
      - IN: dprk_app_img
      - TASK: managed

  - name: dprk_provision_cluster
    type: runSh
    steps:
      - IN: dprk_gitRepo
        # manually trigger the job and not on every commit to the repository
        switch: off
      - IN: dprk-app-def
      - IN: dprk_secret
      - OUT: dprk_secret_opts
      - TASK:
        - script: |
            img_secret_version_file=$(shipctl get_resource_meta dprk_secret_opts)/version.json
            echo $img_secret_version_file
            shipctl replace $img_secret_version_file
            cat $img_secret_version_file

  - name: dprk-app-deploy
    type: deploy
    method: replace
    steps:
      - IN: dprk_provision_cluster
      - IN: dprk_secret_opts
      - IN: dprk-app-def
        switch: off
      - IN: dprk_kube_cluster

  - name: dprk-provision-lb
    type: provision
    steps:
      - IN: dprk_lb
